const questions = [
    { level: 1, question: "What is 2+2?", options: ["3", "4", "5", "6"], answer: "4" },
    { level: 2, question: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], answer: "Paris" },
    { level: 3, question: "Who wrote 'Hamlet'?", options: ["Shakespeare", "Hemingway", "Austen", "Orwell"], answer: "Shakespeare" },
    { level: 4, question: "What is the chemical symbol for water?", options: ["H2O", "O2", "CO2", "NaCl"], answer: "H2O" },
    { level: 5, question: "Which planet is known as the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Saturn"], answer: "Mars" },
    { level: 6, question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Van Gogh", "Da Vinci", "Picasso"], answer: "Da Vinci" },
    { level: 7, question: "What is the largest mammal?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], answer: "Blue Whale" },
    { level: 8, question: "What is the boiling point of water in Celsius?", options: ["90", "100", "120", "150"], answer: "100" },
    { level: 9, question: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: "Nile" },
    { level: 10, question: "Which gas do plants use for photosynthesis?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: "Carbon Dioxide" },
    { level: 11, question: "Which element is represented by 'Fe' on the periodic table?", options: ["Iron", "Fluorine", "Zinc", "Copper"], answer: "Iron" },
    { level: 12, question: "What is the capital of Japan?", options: ["Seoul", "Tokyo", "Beijing", "Bangkok"], answer: "Tokyo" },
    { level: 13, question: "Who discovered gravity?", options: ["Newton", "Einstein", "Galileo", "Tesla"], answer: "Newton" },
    { level: 14, question: "Which sport is known as 'the king of sports'?", options: ["Basketball", "Cricket", "Football", "Tennis"], answer: "Football" },
    { level: 15, question: "What is the square root of 64?", options: ["6", "7", "8", "9"], answer: "8" },
    { level: 16, question: "What is the largest ocean?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: "Pacific" },
    { level: 17, question: "How many bones are in the adult human body?", options: ["206", "210", "180", "220"], answer: "206" },
    { level: 18, question: "What is the capital of Australia?", options: ["Sydney", "Canberra", "Melbourne", "Perth"], answer: "Canberra" },
    { level: 19, question: "Which metal is used in making coins?", options: ["Gold", "Copper", "Aluminium", "Lead"], answer: "Copper" },
    { level: 20, question: "Who developed the theory of relativity?", options: ["Newton", "Einstein", "Hawking", "Bohr"], answer: "Einstein" },
    { level: 21, question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: "Diamond" },
    { level: 22, question: "Which organ is responsible for pumping blood?", options: ["Lungs", "Brain", "Heart", "Kidney"], answer: "Heart" },
    { level: 23, question: "Which animal is known as the 'Ship of the Desert'?", options: ["Camel", "Horse", "Elephant", "Buffalo"], answer: "Camel" },
    { level: 24, question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: "7" },
    { level: 25, question: "Who was the first man to step on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], answer: "Neil Armstrong" },
    { level: 26, question: "What is the smallest prime number?", options: ["1", "2", "3", "5"], answer: "2" },
    { level: 27, question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: "Ottawa" },
    { level: 28, question: "Which planet is closest to the Sun?", options: ["Mars", "Venus", "Mercury", "Jupiter"], answer: "Mercury" },
    { level: 29, question: "What is the national bird of India?", options: ["Sparrow", "Peacock", "Eagle", "Crow"], answer: "Peacock" },
    { level: 30, question: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: "Nitrogen" },
    { level: 31, question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: "6" },
    { level: 32, question: "Which country invented the first printing press?", options: ["Germany", "China", "USA", "UK"], answer: "Germany" },
    { level: 33, question: "What is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Earth"], answer: "Jupiter" },
    { level: 34, question: "Which instrument measures earthquakes?", options: ["Barometer", "Seismometer", "Hygrometer", "Thermometer"], answer: "Seismometer" },
    { level: 35, question: "Which is the longest bone in the human body?", options: ["Femur", "Tibia", "Humerus", "Radius"], answer: "Femur" },
    { level: 36, question: "Who wrote 'The Republic'?", options: ["Plato", "Aristotle", "Socrates", "Hobbes"], answer: "Plato" },
    { level: 37, question: "What is the speed of light?", options: ["300,000 km/s", "150,000 km/s", "1,000 km/s", "500,000 km/s"], answer: "300,000 km/s" },
    { level: 38, question: "Which is the largest desert?", options: ["Sahara", "Antarctica", "Gobi", "Kalahari"], answer: "Antarctica" },
    { level: 39, question: "Who painted 'Starry Night'?", options: ["Da Vinci", "Van Gogh", "Picasso", "Monet"], answer: "Van Gogh" },
    { level: 40, question: "What is the currency of Japan?", options: ["Won", "Rupee", "Yen", "Euro"], answer: "Yen" },
    { level: 41, question: "Which is the only planet that rotates clockwise?", options: ["Mars", "Venus", "Jupiter", "Saturn"], answer: "Venus" },
    { level: 42, question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Central Power Unit", "Core Processing Unit"], answer: "Central Processing Unit" },
    { level: 50, question: "Who discovered penicillin?", options: ["Newton", "Darwin", "Fleming", "Einstein"], answer: "Fleming" }
];

loadQuestion();
